name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # 每天运行一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Information
        run: |
          echo "GitHub username: LucasPUN"
          echo "GitHub token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}"

      - uses: Platane/snk@v2
        with:
          github_user_name: LucasPUN
          outputs: dist/snake.svg

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg

    env:
      GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
