name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # 每天运行一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: 创建 dist 目录
      - name: Create dist directory
        run: |
          mkdir -p dist

      # Step 2: 运行 Platane/snk，生成 snake.svg 到 dist 目录
      - uses: Platane/snk@v3
        with:
          github_user_name: LucasPUN
          outputs: dist/snake.svg

      # Step 3: 初始化 git 仓库并设置远程仓库
      - name: Initialize git repository
        run: |
          git init
          git config --global user.name "LucasPUN"
          git config --global user.email "lucas_3_2_1@hotmail.com"  # 请替换为你的电子邮件
          git remote add origin https://github.com/LucasPUN/LucasPUN.git  # 设置远程仓库
          git fetch origin  # 获取远程仓库信息
          git checkout -b main || git checkout main  # 切换到 main 分支

      # Step 4: 移除 dist/snake.svg 暂时，避免 pull 冲突
      - name: Remove snake.svg temporarily
        run: |
          rm -f dist/snake.svg

      # Step 5: 拉取远程变更并重排提交记录
      - name: Pull and rebase from remote
        run: |
          git pull --rebase origin main

      # Step 6: 重新生成 snake.svg 文件
      - uses: Platane/snk@v3
        with:
          github_user_name: LucasPUN
          outputs: dist/snake.svg

      # Step 7: 提交并推送生成的文件
      - name: Commit and Push Snake Animation
        run: |
          git add dist/snake.svg
          git commit -m "Add snake animation"
          git push https://x-access-token:${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}@github.com/LucasPUN/LucasPUN.git main

      # Step 8: 上传生成的动画文件
      - name: Upload Snake Animation
        uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: dist/snake.svg
