name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # 每天运行一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: 创建 dist 目录
      - name: Create dist directory
        run: |
          mkdir -p dist

      # Step 2: 运行 Platane/snk，生成 snake.svg 到 dist 目录
      - uses: Platane/snk@v3
        with:
          github_user_name: LucasPUN
          outputs: dist/snake.svg

      # Step 3: 初始化 git 仓库并设置远程仓库
      - name: Initialize git repository
        run: |
          git init
          git config --global user.name "LucasPUN"
          git config --global user.email "lucas_3_2_1@hotmail.com"  # 请替换为你的电子邮件
          git remote add origin https://github.com/LucasPUN/LucasPUN.git  # 设置远程仓库
          git fetch origin  # 获取远程仓库信息

      # Step 4: 提交并推送生成的文件
      - name: Commit and Push Snake Animation
        run: |
          git add dist/snake.svg
          git commit -m "Add snake animation"
          git push https://x-access-token:${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}@github.com/LucasPUN/LucasPUN.git master

      # Step 5: 上传生成的动画文件
      - name: Upload Snake Animation
        uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: dist/snake.svg
